FROM php:8.1-apache
COPY ./php/php.ini /usr/local/etc/php/
COPY ./apache/*.conf /etc/apache2/sites-enabled/

RUN apt-get update \
  && apt-get install -y zlib1g-dev unzip libzip-dev vim wget \
  && docker-php-ext-install zip pdo_mysql mysqli exif \
  && docker-php-ext-enable mysqli \
  && cd /etc/apache2/mods-enabled \
  && ln -s ../mods-available/rewrite.load \
  && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
  && apt-get install -y nodejs

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin

WORKDIR /var/www/html